# 应用级别的一些参数配置，服务启动后支持动态更新

local: 
  variable: defg-v1.0.0


#系统级别的一些参数配置，服务启动后不支持动态更新

server:
  #HTTP端口
  port: 9090
      #网络连接超时，单位：毫秒。设置为 0 表示永不超时，这样设置有隐患的。通常可设置为 30000 毫秒。
      #其中和最大连接数相关的参数为maxProcessors 和 acceptCount 。如果要加大并发连接数，应同时加大这两个参数。
  connection-timeout: 5000
  tomcat:
    #URL统一编码
    uri-encoding: UTF-8
    #Tomcat初始化时创建的 socket线程数
    min-spare-threads: 10
            #当tomcat的线程数达到maxThreads后，新的请求就会排队等待，超过排队数的请求会被拒绝
    accept-count: 200
            #同时处理的连接数
    max-connections: 20000
            #同时处理的线程数
    max-threads: 500
    
spring:
  application:
    name: amphilophus-rbac
  cloud:
    config:
      uri: http://localhost:8080/config
      profile: dev
      label: master
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 192.168.179.100
    port: 5672
    username: guest
    password: guest
  zipkin:
    enabled: true
    baseUrl: http://localhost:8080/zipkin
  sleuth:
    sampler:
      probability: 1 #默认值为0.1f，现在为了测试设置100%采集
    zuul:
      enabled: true

eureka:
  instance:
    appname: amphilophus-rbac
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.appname}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:
        - refresh
        - bus-refresh
        - health
        - info
        - hystrix.stream
  health:
    show-details: always

logging:
  level:
    org.springframework: debug
    org.hibernate: debug
    org.mybatis: debug
