spring:
    application:
        name: spring-cloud-client-ribbon
server:
    port: 9091
logging:
    config: classpath:logback.xml
    level:
        org.springframework: error
        org.hibernate: error
        org.mybatis: error
eureka:
    instance:
        hostname: localhost
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8761/eureka/
management:
    endpoints:
        web:
            exposure:
                include: hystrix.stream